/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jillesvangurp.escodegen

import org.gradle.api.Plugin
import org.gradle.api.Project
import com.jillesvangurp.escodegen.opensearch.EsCodeGeneratorOpensearch

open class EsKotlinCodeGenPluginExtension {
    var output: String = "build/generated-kotlin-code"
}

class EsKotlinCodeGenPlugin : Plugin<Project> {
    override fun apply(project: Project) {

        val ext = project.extensions.create("codegen", EsKotlinCodeGenPluginExtension::class.java)
        // Register a task
        project.tasks.register("codegen") { task ->
            task.doLast {
                val esCodeGeneratorOpensearch = EsCodeGeneratorOpensearch(sourceDir = ext.output)
                esCodeGeneratorOpensearch.generateCode()
                val esCodeGenerator = EsCodeGenerator(sourceDir = ext.output)
                esCodeGenerator.generateCode()
            }
        }
    }
}
